### Copyright 2022 Omar Suleiman

steps:

### Deployment by adapt
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          gcloud config set compute/zone us-west2-a

          gcloud container clusters get-credentials omar-moviedb-dev-cluster

          gcloud auth configure-docker --quiet

          export KUBE_DOCKER_REPO=gcr.io/devops-343007 



#adapt run k8s-test --deployID omar-app-dev

  - id: 'deploy'
    name: 'gcr.io/devops-343007/omar-adapt'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          cd deploy
          adapt k8s-test --deployID omar-app-dev


  # - id: 'deploy'
  #   name: 'gcr.io/devops-343007/omar-adapt'
  #   entrypoint: 'adapt'
  #   args: ['cd','deploy','/','run','k8s-test','--deployID','omar-app-dev']
             

### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
