### Copyright 2022 Omar Suleiman

steps:


#adapt run k8s-test --deployID omar-app-dev

# Run Adapt
  - id: 'deploy'
    name: 'gcr.io/omar-devops/adapt'
    entrypoint: 'adapt' 
    env: 
    - 'KUBE_DOCKER_REPO=gcr.io/omar-devops/moviedb-dev'
    args: ['run', 'k8s-test', '--deployID','moviedb-app-dev']
    # args: ['update','omar-app-dev']
    dir: 'deploy'
             

### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
