### Copyright 2022 Omar Suleiman

steps:

### Deployment by adapt
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          gcloud config set compute/zone us-west1-a

          gcloud container clusters get-credentials omar-moviedb-dev-cluster

          gcloud auth configure-docker --quiet

          export KUBE_DOCKER_REPO=gcr.io/devops-343007 

          cd deploy 

          npm install -g @adpt/cli

          adapt run k8s-test --deployID omar-app-dev


#adapt run k8s-test --deployID omar-app-dev


### Run Adapt
  # - id: 'deploy'
  #   name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'adapt'
  #   args: ['run','k8s-test','--deployID','omar-app-dev']


### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
